name: ecocycle_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.1
  google_maps_flutter: ^2.6.1
  shared_preferences: ^2.2.3
  mobile_scanner: ^5.1.2
  provider: ^6.1.2 # Untuk state management
  intl: ^0.19.0
  geolocator: ^10.1.0
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/logo.png
  - assets/google.png
  - assets/facebook.png
  - assets/x.png
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"